"""Add multi_tenant_and_refactor

Revision ID: 7b0dac60f19a
Revises: ea2e8dfba064
Create Date: 2026-01-03 22:22:30.175408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b0dac60f19a'
down_revision: Union[str, Sequence[str], None] = 'ea2e8dfba064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('appointments', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('financial_documents', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_financial_documents_tenant_id'), 'financial_documents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'financial_documents', 'tenants', ['tenant_id'], ['id'])
    op.add_column('medical_records', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_medical_records_tenant_id'), 'medical_records', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'medical_records', 'tenants', ['tenant_id'], ['id'])
    op.add_column('patients', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'])
    op.add_column('tax_analysis', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('tax_analysis', sa.Column('candidate_tokens', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tax_analysis_tenant_id'), 'tax_analysis', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tax_analysis', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('tax_analysis', 'completion_tokens')
    op.add_column('tax_reports', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tax_reports_tenant_id'), 'tax_reports', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tax_reports', 'tenants', ['tenant_id'], ['id'])
    op.add_column('transactions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_column('transactions', 'tenant_id')
    op.drop_constraint(None, 'tax_reports', type_='foreignkey')
    op.drop_index(op.f('ix_tax_reports_tenant_id'), table_name='tax_reports')
    op.drop_column('tax_reports', 'tenant_id')
    op.add_column('tax_analysis', sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tax_analysis', type_='foreignkey')
    op.drop_index(op.f('ix_tax_analysis_tenant_id'), table_name='tax_analysis')
    op.drop_column('tax_analysis', 'candidate_tokens')
    op.drop_column('tax_analysis', 'tenant_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_column('patients', 'tenant_id')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_index(op.f('ix_medical_records_tenant_id'), table_name='medical_records')
    op.drop_column('medical_records', 'tenant_id')
    op.drop_constraint(None, 'financial_documents', type_='foreignkey')
    op.drop_index(op.f('ix_financial_documents_tenant_id'), table_name='financial_documents')
    op.drop_column('financial_documents', 'tenant_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_column('appointments', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
