"""Add CPF and Unified Model

Revision ID: c00a983216d4
Revises: ec31c3c7ed24
Create Date: 2025-12-05 17:13:21.312890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00a983216d4'
down_revision: Union[str, Sequence[str], None] = 'ec31c3c7ed24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cpf', sa.String(), nullable=True))
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_cpf'), 'patients', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_cpf'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.drop_column('patients', 'cpf')
    # ### end Alembic commands ###
