"""Add finance module tables

Revision ID: ea2e8dfba064
Revises: 032ce6441d7b
Create Date: 2026-01-03 21:16:16.893120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea2e8dfba064'
down_revision: Union[str, Sequence[str], None] = '032ce6441d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), server_default='unknown.pdf', nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ingestion_method', sa.String(), nullable=True),
    sa.Column('ingestion_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('competence_month', sa.Integer(), nullable=True),
    sa.Column('competence_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('tax_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('total_deductible', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('competence_month', sa.Integer(), nullable=True),
    sa.Column('competence_year', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['financial_documents.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['financial_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('legal_citation', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('raw_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_cost_brl', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_analysis')
    op.drop_table('transactions')
    op.drop_table('tax_reports')
    op.drop_table('financial_documents')
    # ### end Alembic commands ###
